
import { User, Post, Conversation, Story, Notification } from './types.ts';

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  handle: '@alexr',
  avatar: 'https://picsum.photos/id/64/150/150',
  bio: 'Digital explorer | AI enthusiast | Building the future 🚀',
  followers: 1250,
  following: 432,
};

export const MOCK_USERS: User[] = [
  {
    id: 'u2',
    name: 'Sarah Chen',
    handle: '@sarahc',
    avatar: 'https://picsum.photos/id/65/150/150',
    followers: 8900,
    following: 120,
  },
  {
    id: 'u3',
    name: 'David Miller',
    handle: '@dmiller',
    avatar: 'https://picsum.photos/id/91/150/150',
    followers: 450,
    following: 500,
  },
  {
    id: 'u4',
    name: 'Emily Zhang',
    handle: '@emilyz',
    avatar: 'https://picsum.photos/id/338/150/150',
    followers: 3200,
    following: 150,
  },
  {
    id: 'u5',
    name: 'James Wilson',
    handle: '@jwilson',
    avatar: 'https://picsum.photos/id/334/150/150',
    followers: 1200,
    following: 800,
  },
  {
    id: 'u6',
    name: 'Sofia Rodriguez',
    handle: '@sofiar',
    avatar: 'https://picsum.photos/id/342/150/150',
    followers: 5600,
    following: 430,
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: 's1',
    user: MOCK_USERS[0],
    imageUrl: 'https://picsum.photos/id/129/600/1000',
    timestamp: '2h ago',
    isViewed: false,
  },
  {
    id: 's2',
    user: MOCK_USERS[1],
    imageUrl: 'https://picsum.photos/id/111/600/1000',
    timestamp: '5h ago',
    isViewed: false,
  },
  {
    id: 's3',
    user: MOCK_USERS[2],
    imageUrl: 'https://picsum.photos/id/237/600/1000',
    timestamp: '30m ago',
    isViewed: false,
  },
  {
    id: 's4',
    user: MOCK_USERS[3],
    imageUrl: 'https://picsum.photos/id/48/600/1000',
    timestamp: '1h ago',
    isViewed: false,
  },
  {
    id: 's5',
    user: MOCK_USERS[4],
    imageUrl: 'https://picsum.photos/id/56/600/1000',
    timestamp: '3h ago',
    isViewed: true,
  },
  {
    id: 's6',
    user: MOCK_USERS[0],
    imageUrl: 'https://picsum.photos/id/26/600/1000',
    timestamp: '7h ago',
    isViewed: true,
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'v1',
    user: MOCK_USERS[3],
    content: 'The scale of this cinematic world is breathtaking. Loving the progress on this open-source film project! 🎬✨ #Cinematics #OpenSource',
    likes: 2453,
    reposts: 432,
    quotes: 89,
    comments: [],
    timestamp: '15m ago',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  },
  {
    id: 'v2',
    user: MOCK_USERS[4],
    content: 'Testing out the new motion blur effects. The detail in these renders is getting out of hand! 💻🔥 #DigitalArt #Tech',
    likes: 1890,
    reposts: 211,
    quotes: 45,
    comments: [],
    timestamp: '45m ago',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  },
  {
    id: 'n-p1',
    user: MOCK_USERS[4],
    content: 'Golden hour in the city is something else. 🌆 #UrbanPhotography #Sunset #Vibes',
    likes: 3421,
    reposts: 521,
    quotes: 42,
    comments: [],
    timestamp: '1h ago',
    imageUrls: ['https://picsum.photos/id/10/800/1000'],
  },
  {
    id: 'n-p2',
    user: MOCK_USERS[0],
    content: 'Finally upgraded my workspace. Productivity just went up by 200%! 💻✨ #DeskSetup #Workspace #TechStack',
    likes: 1243,
    reposts: 89,
    quotes: 15,
    comments: [],
    timestamp: '2h ago',
    imageUrls: ['https://picsum.photos/id/20/800/1000'],
  },
  {
    id: 'n-p3',
    user: MOCK_USERS[1],
    content: 'Morning coffee and a good book. Best way to start the day. ☕️📚 #SlowLiving #MorningRoutine',
    likes: 892,
    reposts: 34,
    quotes: 8,
    comments: [],
    timestamp: '3h ago',
    imageUrls: ['https://picsum.photos/id/30/800/1000'],
  },
  {
    id: 'n-p4',
    user: MOCK_USERS[2],
    content: "Missing the neon lights of Tokyo. Can't wait to go back. 🇯🇵🏮 #TravelGram #Tokyo #NightLife",
    likes: 4567,
    reposts: 876,
    quotes: 124,
    comments: [],
    timestamp: '4h ago',
    imageUrls: ['https://picsum.photos/id/40/800/1000'],
  },
  {
    id: 'p1',
    user: MOCK_USERS[0],
    content: 'Just deployed my first AI-powered app! The future of coding is conversational. #AI #Tech',
    likes: 124,
    reposts: 12,
    quotes: 3,
    comments: [
        {
            id: 'c1',
            user: MOCK_USERS[1],
            text: 'This is incredible! Which model did you use for the backend?',
            timestamp: '1h ago'
        },
        {
            id: 'c2',
            user: CURRENT_USER,
            text: 'Thanks Sarah! I used Gemini 2.5, it is blazingly fast.',
            timestamp: '30m ago'
        }
    ],
    timestamp: '5h ago',
    imageUrls: ['https://picsum.photos/id/1/800/1000'],
  },
  {
    id: 'n-p5',
    user: MOCK_USERS[3],
    content: 'Freshly baked sourdough! The crust is perfection. 🥖🔥 #Baking #Sourdough #HomeChef',
    likes: 567,
    reposts: 23,
    quotes: 4,
    comments: [],
    timestamp: '6h ago',
    imageUrls: ['https://picsum.photos/id/50/800/1000'],
  },
  {
    id: 'n-p6',
    user: MOCK_USERS[4],
    content: 'Minimalist architecture at its finest. 🏢⚪️ #Minimalism #Architecture #DesignInspiration',
    likes: 2311,
    reposts: 145,
    quotes: 22,
    comments: [],
    timestamp: '7h ago',
    imageUrls: ['https://picsum.photos/id/60/800/1000'],
  },
  {
    id: 'n-p7',
    user: MOCK_USERS[1],
    content: 'Just finished a 10k run. Feeling energized! 🏃‍♂️💨 #FitnessGoals #Running #Health',
    likes: 754,
    reposts: 12,
    quotes: 2,
    comments: [],
    timestamp: '8h ago',
    imageUrls: ['https://picsum.photos/id/70/800/1000'],
  },
  {
    id: 'p2',
    user: MOCK_USERS[1],
    content: 'Hiking through the Alps was an absolute dream. The air is so fresh up here! 🏔️',
    likes: 892,
    reposts: 56,
    quotes: 12,
    comments: [],
    timestamp: '9h ago',
    imageUrls: ['https://picsum.photos/id/1036/800/1200', 'https://picsum.photos/id/1037/800/1200'],
  },
  {
    id: 'n-p8',
    user: MOCK_USERS[2],
    content: 'Nature is the best artist. Look at these colors! 🌸🌿 #NaturePhotography #Macro #Garden',
    likes: 1543,
    reposts: 78,
    quotes: 11,
    comments: [],
    timestamp: '10h ago',
    imageUrls: ['https://picsum.photos/id/80/800/1000'],
  },
  {
    id: 'n-p9',
    user: MOCK_USERS[3],
    content: 'Throwback to that epic road trip. The open road is calling. 🚗💨 #RoadTrip #Adventure #Explore',
    likes: 3211,
    reposts: 432,
    quotes: 67,
    comments: [],
    timestamp: '12h ago',
    imageUrls: ['https://picsum.photos/id/90/800/1000'],
  },
  {
    id: 'n-p10',
    user: MOCK_USERS[0],
    content: 'Exploring the intersection of art and technology at the new gallery. 🎨🤖 #ArtTech #Exhibit #Innovation',
    likes: 982,
    reposts: 65,
    quotes: 14,
    comments: [],
    timestamp: '1d ago',
    imageUrls: ['https://picsum.photos/id/100/800/1000'],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    user: MOCK_USERS[0],
    lastMessage: 'Did you see the new AI model released yesterday?',
    timestamp: '2m',
    unread: true,
    messages: [
      { id: 'm1', senderId: 'u2', text: 'Hey Alex! Long time no see.', timestamp: '10:00 AM', isOwn: false },
      { id: 'm2', senderId: 'u1', text: 'Hi Sarah! Yeah, been busy with the new project.', timestamp: '10:05 AM', isOwn: true },
      { id: 'm3', senderId: 'u2', text: 'Did you see the new AI model released yesterday?', timestamp: '10:07 AM', isOwn: false }
    ]
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    user: MOCK_USERS[0],
    post: INITIAL_POSTS[0],
    timestamp: '2m ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'repost',
    user: MOCK_USERS[3],
    post: INITIAL_POSTS[0],
    timestamp: '1h ago',
    read: false,
  },
  {
    id: 'n6',
    type: 'follow',
    user: MOCK_USERS[2],
    timestamp: '1d ago',
    read: true,
  }
];
